#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
feh --bg-fill $HOME/Imagenes/wp1.png
wal -i $HOME/Imagenes/wp1.png &
. "${HOME}/.cache/wal/colors.sh"
xsetroot -cursor_name left_ptr &
~/.config/polybar/./launch.sh
bspc config focus_follows_pointer true
picom --experimental-backends &
bspc config border_width 0
