#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a matplotlib state=floating
bspc rule -a Discord desktop='^0' focus=off follow=off

feh --bg-fill $HOME/dotfiles/wallpapers/silHouse.jpg
wal -i $HOME/dotfiles/wallpapers/silHouse.jpg &
. "${HOME}/.cache/wal/colors.sh"
xsetroot -cursor_name left_ptr &
~/dotfiles/polybar/.config/polybar/./launch.sh
bspc config focus_follows_pointer true
picom --experimental-backends &
bspc config border_width 0
wmname LG3D
discord --start-minimized &
eww daemon --restart

# see https://unix.stackexchange.com/a/295652/332452
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

# see https://wiki.archlinux.org/title/GNOME/Keyring#xinitrc
eval $(/usr/bin/gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

# see https://github.com/NixOS/nixpkgs/issues/14966#issuecomment-520083836
mkdir -p "$HOME"/.local/share/keyrings
